name: mdflow
description: A flutter package that provides an easy way to implement a reponsive master detail flow ui for mixed screen sizes.
version: 0.1.0
homepage: https://tonicartos.nz

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  contextx: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
